# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5dbb5a2edd006f0692c173c858095c6695814f24b82b94e0d5709174cdae541ce951f30b0da7db65807448d79be44a0b56a74b268bf10973b554125abee2d2e4

test:
  secret_key_base: d5dc8e02a1d6bcd0f392b653c07712d6a1fd3056829236de3c42dd0d890f515bec318e5222b7d1436c397bd8aedc20f4127a441f5c5fd6ec832538cf9a4c5c7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
